version: '3.4'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.port=9001"
        - "traefik.frontend.rule=Host:mqtt.shackster.uk"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
    volumes:
      - "mqtt_data:/mosquitto/data/"
    ports:
      - "1883:1883"
      - "8883:8883"
    networks:
      - traefik-net
      - mqtt-net
#    configs:
#      - source: mosquitto_conf
#        target: /mosquitto/config/mosquitto.conf
#    secrets:
#      - source: mosquitto_passwd
#        target: /.passwd

configs:
  mosquitto_conf:
    file: ./mosquitto.conf

secrets:
  mosquitto_passwd:
      file: ./passwd

volumes:
  mqtt_data:
    driver: "cloudstor:aws"

networks:
  traefik-net:
    external: true
  mqtt-net:
    external: true
