version: '3.4'

services:
  traefik:
    image: traefik:alpine
    deploy:
      replicas: 1
      labels:
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:traefik.shackster.uk"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_data:/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik-net
    configs:
      - source: traefik_toml
        target: /etc/traefik/traefik.toml
configs:
  traefik_toml:
    file: ./traefik.toml
volumes:
  traefik_data:
    driver: "cloudstor:aws"
networks:
  traefik-net:
    external: true
