version: '3.4'

services:
  portainer:
    image: portainer/portainer
    command: "-H unix:///var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:portainer.shackster.uk"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
